services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - GO_ENV=production
      - GIN_MODE=release
      - DB_MONGO_URI=mongodb://${DB_MONGO_USERNAME}:${DB_MONGO_PASSWORD}@mongo:${DB_MONGO_PORT}/${DB_MONGO_DATABASE}?authSource=admin
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    restart: always
    ports:
      - $DB_MONGO_PORT:$DB_MONGO_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $DB_MONGO_DATABASE
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$DB_MONGO_USERNAME:$DB_MONGO_PASSWORD@mongo:$DB_MONGO_PORT/
      ME_CONFIG_BASICAUTH: false
